# Site settings
title: Journal
email: wizvishak@gmail.com
author: Visahavel Parthasarathy
description: >
  A lightweight theme for your journalling needs
baseurl: ""
url: "http://yourdomain.com"
twitter_username:
github_username:
date_format: "%-d %b %Y"

# Build settings
markdown: redcarpet

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
